apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udp-test
  name: udp-test
  namespace: ac4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: udp-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udp-test
    spec:
      containers:
      - image: la-di.net/udp-test:latest
        imagePullPolicy: Always
        args:
          - --host
          - ladi
        name: udp-test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - name: udp
          containerPort: 2601
          protocol: UDP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
